name: niasync
description: Une app Flutter pour écouter les SMS et envoyer les infos vers un endpoint
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Pour écouter les SMS
  telephony: ^0.2.0

  # HTTP pour envoyer les données au endpoint
  http: ^1.5.0

  # Gestion de l'état (optionnel, mais utile)
  provider: ^6.1.5+1

  shared_preferences: ^2.0.0

  flutter_foreground_task: ^9.1.0
  workmanager: ^0.9.0+3
  device_info_plus: ^12.1.0  
  android_intent_plus: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
