defaultNetwork: 'testnet'
networks:
  [
    {
      name: 'mainnet',
      consensusNodes:
        [
          { url: '35.231.208.148:50211', nodeId: '0.0.3' },
          { url: '35.199.15.177:50211', nodeId: '0.0.4' },
          { url: '35.225.201.195:50211', nodeId: '0.0.5' },
          { url: '35.247.109.135:50211', nodeId: '0.0.6' },
        ],
      mirrorNodeUrl: 'https://mainnet.mirrornode.hedera.com/',
      chainId: 0,
    },
    {
      name: 'previewnet',
      consensusNodes:
        [
          { url: '35.231.208.148:50211', nodeId: '0.0.3' },
          { url: '35.199.15.177:50211', nodeId: '0.0.4' },
          { url: '35.225.201.195:50211', nodeId: '0.0.5' },
          { url: '35.247.109.135:50211', nodeId: '0.0.6' },
        ],
      mirrorNodeUrl: 'https://previewnet.mirrornode.hedera.com/',
      chainId: 0,
    },
    {
      name: 'testnet',
      consensusNodes:
        [
          { url: '0.testnet.hedera.com:50211', nodeId: '0.0.3' },
          { url: '1.testnet.hedera.com:50211', nodeId: '0.0.4' },
          { url: '2.testnet.hedera.com:50211', nodeId: '0.0.5' },
          { url: '3.testnet.hedera.com:50211', nodeId: '0.0.6' },
        ],
      mirrorNodeUrl: 'https://testnet.mirrornode.hedera.com',
      chainId: 0,
    },
  ]
accounts: [{ accountId: '', privateKey: '', network: '', alias: '' }]
