name: Contracts - Test
on: 
  workflow_dispatch:
  push:
    branches: [main]
defaults:
  run:
    working-directory: contracts
jobs:
  test-node:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js TLS 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies Contracts
        run: npm install
        working-directory: contracts
      - name: Test
        # uses: ArtiomTr/jest-coverage-report-action@v2.0.9
        # with:
        #   working-directory: sdk
        #   test-script: npm run test:ci
        working-directory: contracts
        env:
          HEDERA_OPERATOR_ACCOUNT: ${{ secrets.HEDERA_OPERATOR_ACCOUNT }}
          HEDERA_OPERATOR_PUBLICKEY: ${{ secrets.CLIENT_PUBLIC_KEY_ECDSA }}
          HEDERA_OPERATOR_PRIVATEKEY: ${{ secrets.CLIENT_PRIVATE_KEY_ECDSA }}
          HEDERA_OPERATOR_ED25519: false
          HEDERA_NON_OPERATOR_ACCOUNT: ${{ secrets.CLIENT_ACCOUNT_ID_ED25519 }}
          HEDERA_NON_OPERATOR_PUBLICKEY: ${{ secrets.CLIENT_PUBLIC_KEY_ED25519 }}
          HEDERA_NON_OPERATOR_PRIVATEKEY: ${{ secrets.CLIENT_PRIVATE_KEY_ED25519 }}
          HEDERA_NON_OPERATOR_ED25519: true
        run: npm run test