name: SDK - Test
on:
  pull_request:
    branches: [main, release/sdk/**, feature/sdk/**]
    paths:
      - sdk/**
      - .github/workflows/sdk.*.yml
  push:
    branches: [main, release/sdk/**, feature/sdk/**]
    paths:
      - sdk/**
      - .github/workflows/sdk.*.yml
defaults:
  run:
    working-directory: sdk
jobs:
  test-node:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js TLS 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies Contracts
        run: npm install
        working-directory: contracts
      - name: Install dependencies SDK
        run: npm install
      - name: Build Contracts
        run: npm run build
        working-directory: contracts
      - name: LS
        run: ls -la && cd app && ls -la && cd service && ls -la
      - name: Build SDK
        run: npm run build
      - name: Test
        uses: ArtiomTr/jest-coverage-report-action@v2.0.9
        with:
            working-directory: sdk


